package inheritancedemo.module2;

public class TestOverride {
    public static void main(String[] args) {
        SubOverride sb = new SubOverride();
        sb.methodOne(); // calls superclass methodOne()...
        sb.methodTwo(); // calls subclass methodTwo()...
        sb.methodThree(); // calls superclass methodThree()...

        sb.methodThree(1); // calls subclass methodThree()...
    }
}
