package inheritancedemo.module2;

public class TestAssign {
    public static void main(String[] args) {
        SuperOverride sp;
        SubOverride sb;
        sp = new SubOverride(); // this is allowed...
        //sb = new SuperOverride(); // but not this, so comment it out...
        Object o = new SuperOverride(); // this works, since Object is a superclass of all other classes...

        //sp = o; // this won’t work, so comment it out...
        sp = (SuperOverride) o; // but this will...
        sb = (SubOverride) o; // this will compile, but will cause
    }
}
